stages:
  - migrate
  - backup

migrate_database:
  stage: migrate
  script:
    - for f in migrations/*.sql; do
        echo "Применяю миграцию: $f";
        docker exec -i postgres-1c psql -U postgres -d testdb < $f;
      done
  rules:
    - when: always

backup_database:
  stage: backup
  script: docker exec postgres-1c pg_dump -U postgres testdb > backup.sql && ls -la backup.sql
  artifacts:
    paths:
      - "*.sql"
    expire_in: 7 days
  rules:
    - when: always